---
parameters:

  type: terraform

  terraform:
    required_version: '>= 0.13'
    backend:
      s3:
        bucket: "${env}-states"
        key: ${name}
        region: ${aws:region}
        encrypt: true

  kapitan:
    vars:
      target: ${name}

    compile:

      - output_path: terraform
        output_type: json
        prune: false
        input_paths:
          - infrastructure/aws/main.jsonnet
        input_type: jsonnet
