---
parameters:
  infrastructure:
    modules:

      network:
        source: "terraform-aws-modules/vpc/aws"
        version: "3.4.0"
        name: "vpc-${name}"
        cidr: "10.0.0.0/16"
        azs: ["${aws:region}a", "${aws:region}b", "${aws:region}c"]
        private_subnets: ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
        public_subnets: ["10.0.101.0/24", "10.0.102.0/24", "10.0.103.0/24"]
        enable_nat_gateway: false
        single_nat_gateway: true
        public_subnet_tags:
          "kubernetes.io/cluster/${local.cluster_name}": "shared"
          "kubernetes.io/role/elb": "1"
        private_subnet_tags:
          "kubernetes.io/cluster/${local.cluster_name}": "shared"
          "kubernetes.io/role/elb": "1"
        tags:
          Environment: "${env}"
        vpc_tags:
          Name: "vpc-${name}"

      cluster:
        source: "terraform-aws-modules/eks/aws"
        version: "17.1.0"
        cluster_name: "${cluster_name}"
        cluster_version: "1.20"
        subnets: ${infrastructure:modules:network:private_subnets}
        tags:
          Environment: "${env}"
        vpc_id: ${infrastructure:modules:network:name}
        worker_groups:
          - name: "worker-${name}-1"
            instance_type: "t3.small"
            asg_desired_capacity: 2

      app:
        source: "../../../infrastructure/modules/k8s-app"
        cluster_name: "\\${module.cluster.cluster_id}"
        app_name: "${applications:app:app_name}"
        app_chart_path: "${applications:app:app_chart_path}"
