name: Inventory CI/CD
on:
  # enable manual trigger via button in GitHub actions
  workflow_dispatch:
  # enable auto trigger based on path and branch
  push:
    # for main branch
    branches:
      - main
    # if something has changed under this directory
    paths:
      - 'inventory/**'
jobs:
  compile:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set up Kapitan
        run: pip3 install --user --upgrade kapitan
      - name: Kapitan compile
        run: kapitan compile
      - name: Kapitan lint
        run: kapitan lint
      - name: Kapitan validate
        run: kapitan validate
