name: Inventory CI/CD
on:
  # enable manual trigger via button in GitHub actions
  workflow_dispatch:
  # enable auto trigger based on path and branch
  push:
    # for main branch
    branches:
      - main
    # if something has changed under this directory
    paths:
      - 'inventory/**'
jobs:
  compile:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Kapitan compile
        uses: docker://kapicorp/kapitan:ci
        run: kapitan compile
      - name: Kapitan lint
        uses: docker://kapicorp/kapitan:ci
        run: kapitan lint
      - name: Kapitan validate
        uses: docker://kapicorp/kapitan:ci
        run: kapitan validate
