name: Inventory CI/CD
on:
  # enable manual trigger via button in GitHub actions
  workflow_dispatch:
  # enable auto trigger based on path and branch
  push:
    # for main branch
    branches:
      - main
    # if something has changed under this directory
    paths:
      - 'inventory/**'
jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Get kapitan
        run: curl -flLO https://github.com/kapicorp/kapitan/releases/download/v0.29.5/kapitan-linux-amd64 && chmod a+x ./kapitan-linux-amd64
      - name: Kapitan compile
        run: ./kapitan-linux-amd64 compile
      - name: Kapitan lint
        run: ./kapitan-linux-amd64 lint
      - name: Kapitan validate
        run: ./kapitan-linux-amd64 validate
